name: Publish

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      version:
        description: "1.2.3 or 1.2.3-beta.1 (optional if running on a v* tag)"
        required: false

concurrency:
  group: publish-${{ github.ref }}
  cancel-in-progress: false

env:
  CONFIGURATION: Release
  NUGET_SOURCE: https://api.nuget.org/v3/index.json
  ARTIFACTS_DIR: artifacts

jobs:
  pack-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Preflight — verify NuGet API key is available
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          if [ -z "$NUGET_API_KEY" ]; then
            echo "::error::NUGET_API_KEY is not set or not visible to this workflow run."
            echo "Check: repo/organization secrets, environment scope, and that this run is not from a forked PR."
            exit 1
          fi
          echo "::add-mask::$NUGET_API_KEY"
          echo "NuGet API key is present."

      - run: dotnet restore

      - run: dotnet build --no-restore --configuration $CONFIGURATION

      - run: dotnet test  --no-build --configuration $CONFIGURATION --verbosity normal

      - name: Resolve version
        id: ver
        shell: bash
        run: |
          if [[ -n "${{ github.event.inputs.version }}" ]]; then
            VER="${{ github.event.inputs.version }}"
          elif [[ "${GITHUB_REF_TYPE}" == "tag" && "${GITHUB_REF_NAME}" == v* ]]; then
            VER="${GITHUB_REF_NAME#v}"
          else
            echo "::error::No version provided and no v* tag context."; exit 1
          fi
          echo "version=$VER" >> "$GITHUB_OUTPUT"
          echo "Resolved version: $VER"

      - run: mkdir -p "$ARTIFACTS_DIR"

      # Pack each project with the SAME props that will also produce PDBs
      - name: Pack NxGraph
        run: >
          dotnet pack NxGraph/NxGraph.csproj
          --configuration $CONFIGURATION -o $ARTIFACTS_DIR
          -p:ContinuousIntegrationBuild=true -p:Deterministic=true
          -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg
          -p:DebugType=portable
          -p:PackageVersion=${{ steps.ver.outputs.version }}

      - name: Pack NxGraph.Serialization
        run: >
          dotnet pack NxGraph.Serialization/NxGraph.Serialization.csproj
          --configuration $CONFIGURATION -o $ARTIFACTS_DIR
          -p:ContinuousIntegrationBuild=true -p:Deterministic=true
          -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg
          -p:DebugType=portable
          -p:PackageVersion=${{ steps.ver.outputs.version }}

      - name: Pack NxGraph.Serialization.Abstraction
        run: >
          dotnet pack NxGraph.Serialization.Abstraction/NxGraph.Serialization.Abstraction.csproj
          --configuration $CONFIGURATION -o $ARTIFACTS_DIR
          -p:ContinuousIntegrationBuild=true -p:Deterministic=true
          -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg
          -p:DebugType=portable
          -p:PackageVersion=${{ steps.ver.outputs.version }}

      - name: List artifacts
        run: ls -al "$ARTIFACTS_DIR"

      # Quick validation to catch mismatches before upload
      - name: Validate package and symbol contents
        run: |
          echo "== Listing assemblies in nupkg =="
          for f in $ARTIFACTS_DIR/*.nupkg; do
            echo "---- $(basename "$f")"; unzip -l "$f" | grep -E '(^|/)(lib|ref|runtimes)/' || true
          done
          echo "== Listing PDBs in snupkg =="
          for f in $ARTIFACTS_DIR/*.snupkg; do
            echo "---- $(basename "$f")"; unzip -l "$f" | grep -E '\.pdb$' || true
          done

      - name: Push .nupkg to nuget.org
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: >
          dotnet nuget push "$ARTIFACTS_DIR"/*.nupkg
          --api-key "$NUGET_API_KEY"
          --source "$NUGET_SOURCE"
          --skip-duplicate

      - name: Push .snupkg (symbols)
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: >
          dotnet nuget push "$ARTIFACTS_DIR"/*.snupkg
          --api-key "$NUGET_API_KEY"
          --source "$NUGET_SOURCE"
          --skip-duplicate

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: nuget-${{ steps.ver.outputs.version }}
          path: |
            ${{ env.ARTIFACTS_DIR }}/*.nupkg
            ${{ env.ARTIFACTS_DIR }}/*.snupkg
